# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://2016.phpsouthcoast.co.uk
title: PHP South Coast 2016
email: your-email@domain.com
author: PHP South Coast
description:
  Join us for a PHP Conference on the south coast, UK in Summer 2016!
keywords: "PHP, Conference, South coast, Hampshire, Portsmouth, England"
copyright: 'Copyright &copy; 2016 PHP South Coast conference. All Rights Reserved.'
credits: ''
confDate: Saturday 11th June 2016

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/phpsouthcoast
  - title: github
    url: https://github.com/phphants/php-south-coast-2016
